### ISSUE TITLE
No electric generate in example generator

### ISSUE THREAD

**Issue by Galaxy-VN** [NCBPFluffyBear/SlimeCustomizer#11]
## Description (Required)
The example generator does not consume the spruce sign

## Steps to reproduce the Issue (Required)
- place down the example generator
- put spruce sign in
- nothing happen

## Expected behavior (Required)
I need it to cosume the input and starting generate electric

## Server Log / Error Report
https://pastebin.com/CDpDLWHE

## Environment (Required)

 - Minecraft Version: Paper 778
 - Slimefun Version: DEV 939 (git 57f75)
 - Plugin Version: DEV 8 (git 6fe1c)

**Comment by NCBPFluffyBear** [comment]
According to that error, it seems the plugin did not initialize correctly. A simple server restart should do. Reopen this issue if that does not fix the problem.
