### ISSUE TITLE
how to fix [11:45:07 ERROR]: [SlimeCustomizer] The speed-in-seconds for recipe 1 for MACHINE must be a positive integer!

### ISSUE THREAD

**Issue by Ohminecraft** [NCBPFluffyBear/SlimeCustomizer#15]
## Environment (Required)

 - Minecraft Version:
 - CS-CoreLib Version:
 - Slimefun Version:
 - Plugin Version:

**Comment by Ohminecraft** [comment]
how to fix plz

**Comment by NCBPFluffyBear** [comment]
How do I know what to fix if I don't know what you did wrong? Send the relevant configs

**Comment by NCBPFluffyBear** [comment]
No response over 15 days
