### ISSUE TITLE
support

### ISSUE THREAD

**Issue by haiman233** [NCBPFluffyBear/SlimeCustomizer#17]
this plugin is very useful！but support 1.17 or the newest  slimefun please！

**Comment by NCBPFluffyBear** [comment]
I haven't encountered any issues running SC on 1.17. If you have any errors, you need to share them.

**Comment by haiman233** [comment]
![image](https://user-images.githubusercontent.com/83174104/129136241-989b1e33-40d4-4537-b79e-7b9903696995.png)

**Comment by NCBPFluffyBear** [comment]
This looks like a saveditem initialization error. If you saved an item in a later version and then you are downgrading to 1.16, there will be issues. Going form 1.16 to 1.17 should have zero issues. If you are having issues, I suggest you re-save the items.
