### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by haiman233** [NCBPFluffyBear/SlimeCustomizer#18]
Minecraft version:1.16.5
slimefun version:rc24
Java 11
plugin version:the newest
When the two input slots are empty(have output items),the machine will disappear directly after being put down.

**Comment by NCBPFluffyBear** [comment]
I don't understand what you are trying to say. Can you try explaining it in more detail and give me steps to reproduce the issue? Also attach relevant config files.

**Comment by haiman233** [comment]
[new 1.txt](https://github.com/NCBPFluffyBear/SlimeCustomizer/files/6971906/new.1.txt)

**Comment by NCBPFluffyBear** [comment]
I don't understand what you are trying to say. Can you try explaining it in more detail and give me steps to reproduce the issue?

**Comment by NCBPFluffyBear** [comment]
This is a machine with no inputs. You need to have some kind of input in your machines. There is a planned feature for resource generator machines which take no inputs, but I am not sure when that will be added.
