### ISSUE TITLE
Unknown error upon server startup

### ISSUE THREAD

**Issue by Boomer-1** [NCBPFluffyBear/SlimeCustomizer#2]
## Description (Required)

I am not a programmer, so I don't know what this error is in reference to. It first appeared after I removed CS Core Lib.

## Steps to reproduce the Issue (Required)

no idea what is causing it

## Server Log / Error Report

https://pastebin.com/T7sKRYDU

## Environment (Required)

 - Minecraft Version: 1.16.5
 - CS-CoreLib Version: removed 
 - Slimefun Version: Dev 803
 - Plugin Version: Dev 1

**Comment by NCBPFluffyBear** [comment]
Fixed in latest, thank you.
