### ISSUE TITLE
the plugin unloaded

### ISSUE THREAD

**Issue by haiman233** [NCBPFluffyBear/SlimeCustomizer#24]
![-5f32902fc41721d1](https://user-images.githubusercontent.com/83174104/147385624-0df42a43-b967-4888-b911-150f2de64d0b.jpg)
![-29f7054328d782f3](https://user-images.githubusercontent.com/83174104/147385625-4789967a-73c7-411f-9e64-75c4eab1756c.png)
![23c7886a2431e9ac](https://user-images.githubusercontent.com/83174104/147385627-adcd3f51-b106-42aa-aab9-a091a4c5797d.png)

**Comment by NCBPFluffyBear** [comment]
Your SlimeCustomizer version is not up to date; please update here: https://thebusybiscuit.github.io/builds/NCBPFluffyBear/SlimeCustomizer/master
