### ISSUE TITLE
Machines won't work with 1 ingredient in 2 input slots

### ISSUE THREAD

**Issue by QiPaoStart** [NCBPFluffyBear/SlimeCustomizer#28]
## Description (Required)

The machine needs same ingredient in 2 input slots, and I put them in the slots.
Then the progress bar won't appear and the machine won't work.

## Steps to reproduce the Issue (Required)

1. Edit a machine in machines.yml which needs 1 ingredient in 2 input slots (The bug will still appear when the input item belongs to Slimefun)
![image](https://user-images.githubusercontent.com/83635508/153110490-cac5643b-39dc-48da-82d7-4ea016c4b2d0.png)
2. Start the server and put the required ingredients in the machine
![2022-02-09_10 32 29](https://user-images.githubusercontent.com/83635508/153110806-ab10fb15-02fa-41f2-891c-5e42dbe6c034.png)
And the machine won't work at all!

## Expected behavior (Required)

Please fix this bug

## Environment (Required)

 - Minecraft Version: paper server, 1.16.5 (git-Paper-651)
 - CS-CoreLib Version: -
 - Slimefun Version: v4.9-release-2022.2 (Chinese version, [https://github.com/StarWishsama/Slimefun4](https://github.com/StarWishsama/Slimefun4))
 - Plugin Version: DEV 23 (git c1038)

**Comment by QiPaoStart** [comment]
https://pastebin.com/MShser3q

**Comment by NCBPFluffyBear** [comment]
After some experimentation, I believe that this is not possible. This plugin only interfaces with Slimefun's API for recipes, and it will not recognize this kind of a recipe.

Instead, I suggest you add an intermediate crafting step, like 64 diamonds to 1 `X`, then make the machine require 2 `X`, effectively requiring 128 diamonds.
