### ISSUE TITLE
Multiple Inputs button causing console error/not working

### ISSUE THREAD

**Issue by Azakaturan** [NCBPFluffyBear/SlimeCustomizer#29]
## Description (Required)
When clicking the 'Multiple Inputs' button on a machine with multiple inputs for an output, it outputs an inventory click event error in console and doesn't work

## Steps to reproduce the Issue (Required)
Make a machine with multiple inputs/1 output
Click Multiple Input button
https://gyazo.com/c13258d8f3b8d631a4ad84022d2e658e

## Expected behavior (Required)
Button to button

## Server Log / Error Report
https://pastebin.com/LV2zebTH

## Environment (Required)
![image](https://user-images.githubusercontent.com/79327162/158090989-4b96ca80-a331-47ee-88bf-29b9f95a2c03.png)

 - Minecraft Version: 1.18.1
 - CS-CoreLib Version: N/A
 - Slimefun Version: 1005
 - Plugin Version:  23

**Comment by NCBPFluffyBear** [comment]
Fixed in d6f396940b95f946a1b4241788940a0d8c4a220c
