### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by PhoenixCodingStuff** [NCBPFluffyBear/SlimeCustomizer#30]
## Description 
Error on console on startup

## Steps to reproduce the Issue 
Add Slimefun DEV - 1008 (git 020094e0) and SlimeCustomizer vDEV - 24 (git f6aa53e9) to the plugins folder
Start the server

## Expected behavior 
No error on startup

## Server Log / Error Report
https://paste.walshy.dev/wwrcuTc6Ndw9
https://paste.walshy.dev/leTkqgJ7XTLG

## Config Files
Can I DM it to you on discord instead?

## Environment
[Wed 15:25:33 INFO ] This Server uses the following setup of Slimefun:
Paper git-Paper-216 (MC: 1.18.1)
Slimefun DEV - 1008 (git 020094e0)
Metrics-Module #28
Java 17
Installed Addons: (30)
  GlobalWarming vDEV - 11 (git 73ff77d4)
  SlimeBot v1.1.0
  Networks vDEV - 33 (git 3474aec2)
  CrystamaeHistoria vDEV - 60 (git 371baa3e)
  AureliumSkills vBeta 1.2.10
  FoxyMachines vDEV - 55 (git c1b69ec7)
  FNAmplifications vDEV - 57 (git 96c5d943)
  SimpleMaterialGenerators vDEV - 4 (git 5543cc8f)
  DynaTech vDEV - 160 (git e1075a1c)
  SFAdvancements vDEV - 9 (git e90d0f72)
  CMILib v1.1.2.3
  InfinityExpansion vDEV - 137 (git 4b326e08)
  ElectricSpawners vDEV - 23 (git 6ec96773)
  MobCapturer vDEV - 17 (git c21b00a5)
  SlimyTreeTaps vDEV - 20 (git 963f0383)
  FlowerPower vDEV - 13 (git 06ad45dc)
  SlimeTinker vDEV - 72 (git bb2ef153)
  TranscEndence vDEV - 40 (git cfc98363)
  FluffyMachines vDEV - 108 (git 7bfc4f0c)
  HotbarPets vDEV - 38 (git fa6c871d)
  SlimefunLuckyBlocks vDEV - 36 (git 60f0c8dc)
  ExoticGarden vDEV - 78 (git 7f9a5f63)
  DankTech2 vDEV - 4 (git 803760fb)
  Liquid vDEV - 14 (git 0f5346bf)
  SlimeCustomizer vDEV - 24 (git f6aa53e9)
  UltimateClaims v1.9.1
  LiteXpansion vDEV - 174 (git e36d509d)
  ElementManipulation vDEV - 15 (git 9b99afba)
  SoulJars vDEV - 23 (git b8358a1f)
  PotionExpansion vDEV - 5 (git e2cfcd8a)

 - Minecraft Version: 1.18.1
 - CS-CoreLib Version: N/A
 - Slimefun Version: Slimefun DEV - 1008 (git 020094e0) 
 - Plugin Version: SlimeCustomizer vDEV - 24 (git f6aa53e9)

**Comment by PhoenixCodingStuff** [comment]
There is only 1 error put into 2 pastebin links since could not send both in 1

**Comment by NCBPFluffyBear** [comment]
Try redownloading and restarting the server. When it says zip file closed it's typically an issue with corruption or messingg around with plugin jars before the server is stopped/before the server is fully started

**Comment by PhoenixCodingStuff** [comment]
Yea will do and get back to you
