### ISSUE TITLE
Crafting items saved with customizer doesn't apply slimefun tags to said item.

### ISSUE THREAD

**Issue by GentlemanCheesy** [NCBPFluffyBear/SlimeCustomizer#33]
## Description (Required)
When crafting items with an enhanced crafting table, the saved item set as the output doesn't receive the Slimefun tag. This leads to some problems with placing saved items since they don't have said nbt.

## Steps to reproduce the Issue (Required)
Create a recipe using a saved item as its recipe output and craft it, its result should have incorrect nbt.

## Expected behavior (Required)
Preferably the crafted item should have the same nbt as given to it if I used /slimefun cheat to obtain it. 

## Server Log / Error Report
No errors in my logs as far as I have seen.

## Config Files
items.yml example: https://pastebin.com/h83RWXsa
saved item related to example: https://pastebin.com/tmziKBA2

## Environment (Required)
/sf version via console: https://pastebin.com/eE34v3Md

 - Minecraft Version: paper 1.18.2
 - CS-CoreLib Version: n/a
 - Slimefun Version: DEV 1009
 - Plugin Version:  Build 25

**Comment by NCBPFluffyBear** [comment]
That is intentional so that saveditems from other plugins don't have slimefun tags. If you want to craft a slimefun item, use SLIMEFUN instead of SAVEDITEM.
