### ISSUE TITLE
items and blocks from version 1.19

### ISSUE THREAD

**Issue by rlcoldx** [NCBPFluffyBear/SlimeCustomizer#44]
The plugin does not recognize the items and blocks in version 1.19 in the recipes. Update isso please.

**Comment by NCBPFluffyBear** [comment]
Hi, it looks like a majority of servers are running this plugin on 1.19, could you attach any relevant console errors and configuration files please?

**Comment by rlcoldx** [comment]
> Hi, it looks like a majority of servers are running this plugin on 1.19, could you attach any relevant console errors and configuration files please?

The plugin does not recognize 1.19 items anywhere in the recipe.

![Screenshot_1](https://user-images.githubusercontent.com/79703050/210007399-dfa75039-f4a8-4384-8a02-31d8a29d0a66.png)

`MANGROVE_MACHINE:
  category: slime_customizer
  machine-name: '&bMangrove Tree Grower'
  machine-lore:
  - '&7Essa maquina faz crescer a arvore do mangue'
  block-type: STRIPPED_OAK_WOOD
  progress-bar-item: FLINT_AND_STEEL
  stats:
    energy-consumption: 1000
    energy-buffer: 5000
  crafting-recipe-type: ENHANCED_CRAFTING_TABLE
  crafting-recipe:
    '1':
      type: SLIMEFUN
      id: HARDENED_GLASS
      amount: 1
    '2':
      type: SLIMEFUN
      id: HARDENED_GLASS
      amount: 1
    '3':
      type: SLIMEFUN
      id: HARDENED_GLASS
      amount: 1
    '4':
      type: SLIMEFUN
      id: MAGNONIUM
      amount: 1
    '5':
      type: VANILLA
      id: GRASS_BLOCK
      amount: 1
    '6':
      type: SLIMEFUN
      id: MAGNONIUM
      amount: 1
    '7':
      type: SLIMEFUN
      id: MACHINE_CIRCUIT
      amount: 1
    '8':
      type: SLIMEFUN
      id: MACHINE_CORE
      amount: 1
    '9':
      type: SLIMEFUN
      id: MACHINE_CIRCUIT
      amount: 1
  recipes:
    '1':
      speed-in-seconds: 60
      input:
        '1':
          type: VANILLA
          id: MONGROVE_PROPAGULE
          amount: 1
      output:
        '1':
          type: VANILLA
          id: MONGROVE_LOG
          amount: 4
        '2':
          type: VANILLA
          id: MONGROVE_PROPAGULE
          amount: 1
`

**Comment by NCBPFluffyBear** [comment]
Hey, it seems you typed MONGROVE instead of MANGROVE

Please let me know of this fixes your issue

**Comment by rlcoldx** [comment]
> Hey, it seems you typed MONGROVE instead of MANGROVE
> 
> Please let me know of this fixes your issue

Ah sorry, the problem of typing too fast. But I fixed it to MANGROVE and restarted but now the below error appears.
![Screenshot_3](https://user-images.githubusercontent.com/79703050/210012384-62c13bd1-9e60-47b6-9cf6-4da8577fb129.png)

**Comment by NCBPFluffyBear** [comment]
Please send your updated config as well

**Comment by rlcoldx** [comment]
> Hey, it seems you typed MONGROVE instead of MANGROVE
> 
> Please let me know of this fixes your issue

i'm sorry 
https://pastebin.com/mmdKSphi

**Comment by NCBPFluffyBear** [comment]
If you choose to have only one input, specify the second input as NONE. For an example, please refer to the example machine in the readme.

**Comment by rlcoldx** [comment]
Perfect, now it works perfectly. https://pastebin.com/XMUeNAbw

So there's no way to make the machine have only one input and several outputs?
Or doubt it is. There is no way to make the input item 1 not be consumed in the process. Like a generator?

**Comment by NCBPFluffyBear** [comment]
> So there's no way to make the machine have only one input and several outputs?

Isn't that what you have just achieved? Your second input is "NONE", so there is just 1 input.

> There is no way to make the input item 1 not be consumed in the process. Like a generator?

Readme: https://github.com/NCBPFluffyBear/SlimeCustomizer#adding-your-generator
Just set the output to NONE, like you did for the second input.

For further assistance on setting up the generator, please request help in the [Slimefun Addon Community Discord](https://discord.gg/SqD3gg5SAU)
If the original issue has been resolved, please close this issue. Thank you!

**Comment by NCBPFluffyBear** [comment]
oops i didnt mean to hit that
