### ISSUE TITLE
is NOT a bug, is a QUESTION and SUGGESTION

### ISSUE THREAD

**Issue by TheExotik** [NCBPFluffyBear/SlimeCustomizer#45]
hey, so i'm new in Slimefun thing, and also very new in codes...
i was just wondering if is possible to disable this 
![image](https://user-images.githubusercontent.com/97954441/218852876-069d9637-c521-41fe-b120-f3bb1faf4e8d.png)
i want to use my custom lore, and this kinda "desnecessary" for me, can i do something to disable? maybe in source code (please if this is a possibility tell-me how i do cause i don't know) or if have i dunno some config i can edit.

purpue 1.19.3
sc dev 29 git81552

Thanks guys, and thank you for the addon, is very cool.
also, other question

can i add a "porcentage %" in item Output? like
input = 1 gravel --> output= 20% to get iron, and 80% to get coal
something like that

again thank you guys, and sorry for create a "issue report" i still learning how Github works and i don't find your discord....

**Comment by NCBPFluffyBear** [comment]
Hi,

You unfortunately can not disable that lore, but it is possible recompile the plugin with it removed. I am not able to assist you right now, but that lore is added in the machine/generator's respective setup file. 

Currently you can not add percentages to items, but it is a planned feature for the "future".

**Comment by NCBPFluffyBear** [comment]
Hi, currently 2:2 is the maximum supported input to output rate. There isn't really a plan on expanding this feature right now, but it's not impossible.

**Comment by TheExotik** [comment]
oh ok, isn't a big deal, again thanks for support, ur addons is very cool <3 i loved making some machines ^^ gonna close the ticket, have a good day xD
